public class LongFormSpecialOffer {
	public String offerId {get; set;}
    public String offerContentKey {get; set;}
    public String productName {get; set;}
    public String offerDiscount {get; set;}
    public String offerDiscountRatePer {get; set;}
    public String offerIsBased {get; set;}
    public String offerTime {get; set;}
    public String offerVolume {get; set;}
    public String offerFuelType {get; set;}
    public String offerCountry {get; set;}
    public String offerSelectionBtnStatus {get; set;}
    public String offerRemoveBtnStatus {get; set;}
    public String offerCancelBtnStatus {get; set;}
    public String homeMapSelectionBtnStatus {get; set;}
    public String offerStation {get; set;}
}