public class LongFormCard {
    public String sfCardId;   
    public String categoryCard {get; set;}
    public Boolean pumpOutsideCountry {get; set;}
    public Boolean pumpAtPartners {get; set;}
    public Boolean cardIsConfigurated {get; set;}
    public Boolean displayTechnicalParamsBlock {get; set;}
    public Boolean displayCompanyNameField {get; set;}
    public Boolean techParamsIsConfigurated {get; set;}
    public String selectedDriverNameOrCarNumber {get; set;}
    public String driverNameOrCarNumberInputValue {get; set;}
    public String companyNameInputValue {get; set;}
    public String emitDate {get; set;}
    public String selectedTypeOfCar {get; set;}
    public Boolean needOdometerOptions {get; set;}
    public String activeCardConfigStepMobile {get; set;}
}